// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.subsystems;


import frc.robot.Robot;
import frc.robot.RobotContainer;
import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.PWMTalonFX;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.drive.MecanumDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

import edu.wpi.first.wpilibj.XboxController;

/**
 *
 */
public class Drivetrain extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private PWMTalonFX speedController1;
private PWMTalonFX speedController2;
private PWMTalonFX speedController3;
private PWMTalonFX speedController4;
private MecanumDrive mecanumDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    /**
    *
    */
    public Drivetrain() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
speedController1 = new PWMTalonFX(0);
 addChild("Speed Controller 1",speedController1);
 speedController1.setInverted(false);

speedController2 = new PWMTalonFX(1);
 addChild("Speed Controller 2",speedController2);
 speedController2.setInverted(false);

speedController3 = new PWMTalonFX(2);
 addChild("Speed Controller 3",speedController3);
 speedController3.setInverted(false);

speedController4 = new PWMTalonFX(3);
 addChild("Speed Controller 4",speedController4);
 speedController4.setInverted(false);

MecanumDrive mecanumDrive = new MecanumDrive(speedController1, speedController2,
speedController3, speedController4);
 addChild("mecanumDrive",mecanumDrive);
 mecanumDrive.setSafetyEnabled(true);
mecanumDrive.setExpiration(0.1);
mecanumDrive.setMaxOutput(1.0);



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    private boolean zero = true;

    public void setXboxController(XboxController xbox) {
        if(xbox.getAButton()) {
            zero = false;
            RobotContainer.getInstance().m_sensors.zeroYaw();
        } else if (xbox.getBButton()) {
            zero = true;
        } else {
            double x = xbox.getRawAxis(4);
            double y = -xbox.getRawAxis(5);
            double z = xbox.getRawAxis(3)-xbox.getRawAxis(2);
            double g = -(zero?0:RobotContainer.getInstance().m_sensors.getAngle());
            mecanumDrive.driveCartesian(x, y, z, g);
        }
    }

    public void stop() {
        mecanumDrive.driveCartesian(0, 0, 0);
    }

}

